# Generated by Django 3.2.7 on 2022-02-19 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHAT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=20),
        ),
    ]
