# Generated by Django 3.2.7 on 2022-01-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_users_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutioninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
                ('medium', models.CharField(max_length=200, null=True)),
                ('subjects', models.CharField(max_length=200, null=True)),
                ('cls', models.CharField(max_length=200, null=True)),
                ('salary', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
