# Generated by Django 3.2.7 on 2022-01-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='cls',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='medium',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='salary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='subjects',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='proimg',
            field=models.ImageField(upload_to='STATIC\\images'),
        ),
    ]
