# Generated by Django 3.2.7 on 2022-01-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_auto_20220105_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=200, null=True)),
                ('appliedby', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
