# Generated by Django 3.2.7 on 2022-01-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_appliedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
