# Generated by Django 3.2.7 on 2022-01-11 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_studentdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
