# Generated by Django 3.2.7 on 2022-01-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0010_auto_20220112_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forapproval',
            name='certificate1',
            field=models.ImageField(upload_to='STATIC\\cert1'),
        ),
        migrations.AlterField(
            model_name='forapproval',
            name='certificate2',
            field=models.ImageField(upload_to='STATIC\\cert2'),
        ),
        migrations.AlterField(
            model_name='forapproval',
            name='tutorimg',
            field=models.ImageField(upload_to='STATIC\tutorprofile'),
        ),
    ]
