# Generated by Django 3.2.7 on 2022-01-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0011_auto_20220112_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forapproval',
            name='certificate1',
            field=models.ImageField(upload_to='STATIC\\images'),
        ),
        migrations.AlterField(
            model_name='forapproval',
            name='certificate2',
            field=models.ImageField(upload_to='STATIC\\images'),
        ),
        migrations.AlterField(
            model_name='forapproval',
            name='tutorimg',
            field=models.ImageField(upload_to='STATIC\\images'),
        ),
    ]
