# Generated by Django 3.2.7 on 2022-01-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0012_auto_20220113_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutordata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField()),
                ('account', models.CharField(choices=[('Teacher', 'Teacher'), ('Parent', 'Parent')], max_length=10, null=True)),
                ('tutorimg', models.ImageField(upload_to='STATIC\\images')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('institute', models.CharField(max_length=200, null=True)),
                ('medium', models.CharField(max_length=200, null=True)),
                ('subjects', models.CharField(max_length=200, null=True)),
                ('cls', models.CharField(max_length=200, null=True)),
                ('salary', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('certificate1', models.ImageField(upload_to='STATIC\\images')),
                ('certificate2', models.ImageField(upload_to='STATIC\\images')),
            ],
        ),
        migrations.RemoveField(
            model_name='forapproval',
            name='certificate2',
        ),
    ]
