# Generated by Django 3.2.7 on 2022-01-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0013_auto_20220117_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='forapproval',
            name='certificate2',
            field=models.ImageField(null=True, upload_to='STATIC\\images'),
        ),
    ]
