# Generated by Django 3.2.7 on 2022-01-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0014_forapproval_certificate2'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedlist',
            name='appliedname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
