# Generated by Django 3.2.7 on 2022-01-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0015_appliedlist_appliedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='deadline',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
