# Generated by Django 3.2.7 on 2022-01-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0016_studentdata_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='proimg',
            field=models.ImageField(null=True, upload_to='STATIC\\images'),
        ),
    ]
